"""Generate formats/temetra_csv_fields.yaml from the Temetra NAM CSV File Format Guide.

Usage:
    pdftotext -layout Temetra_NAM_CSV_File_Format_Guide.pdf nam.txt
    python tools/extract_temetra_csv_guide.py nam.txt src/rsvalidator/formats/temetra_csv_fields.yaml

Reads "Available CSV File Format Fields" (LDI-0665 REV 002, pages 15-32) and
Tags (ADDTAG values) are few and hand-written in formats/temetra.yaml. Page
numbers are the guide's own ("Page N of 56"), which equal PDF pages. Review the output by
hand after regenerating; corrections belong in formats/temetra.yaml.
"""

from __future__ import annotations

import re
import sys

import yaml

FIELD_PAGES = range(15, 33)
HEADER = re.compile(r"^\s*Field\s{2,}Description\s{2,}Field Type\s{2,}Max\s{2,}Required\s{2,}Available")
TAG_SECTION = re.compile(r"^\s*(Customer Tags|Meter Tags|Cellular Tags|Scheduled Meter Tags)\s*$")
FIELD_NAME = re.compile(r"^ {0,3}([A-Z][A-Z0-9_]+)(\s|$)")
FOOTER = ("LDI-0665", "Temetra NAM CSV File Format Guide")


def columns(header: str) -> list[int]:
    return [header.index(h) for h in ("Description", "Field Type", "Max", "Required", "Available")]


def cut(line: str, cols: list[int]) -> list[str]:
    bounds = [0] + cols + [10_000]
    return [line[bounds[i]:bounds[i + 1]].strip() for i in range(len(bounds) - 1)]


def read_fields(pages):
    fields: dict[str, dict] = {}
    current, current_name, lines_in = None, None, 0
    for page in FIELD_PAGES:
        lines = [ln for ln in pages[page - 1].splitlines() if not any(f in ln for f in FOOTER)]
        cols = None
        for ln in lines:
            if HEADER.match(ln):
                cols = columns(ln)
                continue
            if cols is None or not ln.strip() or ln.strip() == "Values":
                continue
            if TAG_SECTION.match(ln):
                return fields
            parts = cut(ln, cols)
            name_part = parts[0]
            if current is not None and lines_in == 1 and re.fullmatch(r"[A-Z0-9_]+", name_part or "-") and (
                    current_name.endswith("_") or len(current_name) >= 17):
                # Field name wrapped onto a second line (e.g. METERNOMINALSIZE_ / IMPERIAL).
                fields[current_name + name_part] = fields.pop(current_name)
                current_name += name_part
                name_part = ""
            elif FIELD_NAME.match(ln) and re.fullmatch(r"[A-Z][A-Z0-9_]+", name_part):
                current_name = name_part
                current = fields.setdefault(name_part, {"page": page, "desc": [], "type": [], "max": [],
                                                        "required": [], "values": []})
                lines_in = 0
            if current is None:
                continue
            lines_in += 1
            for key, text in zip(("desc", "type", "max", "required", "values"), parts[1:]):
                if text:
                    current[key].append(text)
    return fields


def clean_field(name: str, raw: dict) -> dict:
    j = lambda xs: " ".join(xs).strip()
    out = {"name": name, "page": raw["page"]}
    if raw["type"]:
        out["type"] = j(raw["type"])
    mx = j(raw["max"])
    if mx:
        out["max"] = int(mx) if mx.isdigit() else mx
    req = j(raw["required"])
    if req:
        out["required"] = req
    if raw["values"]:
        out["values"] = j(raw["values"])
    out["desc"] = j(raw["desc"])
    return out


def main(src: str, dest: str):
    pages = open(src, encoding="utf-8").read().split("\f")
    fields = [clean_field(n, r) for n, r in read_fields(pages).items()]
    header = (
        "# GENERATED by tools/extract_temetra_csv_guide.py from the Temetra NAM CSV File Format\n"
        "# Guide (LDI-0665 REV 002, December 2024). Page numbers are the guide's pages.\n"
        "# Hand corrections belong in formats/temetra.yaml, not here.\n"
    )
    with open(dest, "w") as f:
        f.write(header)
        yaml.safe_dump({"fields": fields}, f, sort_keys=False, width=110, allow_unicode=True)
    print(f"{len(fields)} fields")
    for fl in fields:
        print(f"  {fl['name']:28} p.{fl['page']:<3} {fl.get('type', '?'):16} max={fl.get('max', '')!s:10} "
              f"req={fl.get('required', '')!s:5} values={fl.get('values', '')[:50]}")


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
